rot_calib_window_size: 10000
alpha: 5
q_dot_3sigma: 0.01
cal_mask: [false, true, true, false] # which components of rotor's dynamics to calibrate: [K_t, K_d0, K_d1, rot_MoI]
lambda: [0.1, 0.001, 0.001, 0.1]
lambda_high: [1e14, 1e6, 1e6, 1e14]
mov_avrg_cutoff_freq: 5.0
set_ig_to_prev_sol: false

# ****** SINGLE JOINT ****** #

jnt_list: ["J2_E"] # joints to be moved

red_ratio: [0.00625]  # gear reduction ratio of the actuator (always <=1)

K_t: [0.14]
rotor_MoI: [3.26e-4]
K_d0: [0.0]
K_d1: [0.0]

K_t_ig: [0.14]
rot_MoI_ig: [3.26e-4]
K_d0_ig: [0.0] # initial guess for the static friction torque coefficient ( tau_d0 = K_d* sign(joint_vel) )
K_d1_ig: [0.0] # initial guess for the dynamical friction torque coefficient ( tau_d1 = K_d* joint_vel )

K_t_nom: [0.14]
rot_MoI_nom: [3.26e-4]
K_d0_nom: [0.0] # initial guess for the static friction torque coefficient ( tau_d0 = K_d* sign(joint_vel) )
K_d1_nom: [0.0] # initial guess for the dynamical friction torque coefficient ( tau_d1 = K_d* joint_vel )

# ****** ALL JOINTS ****** #

#jnt_list: ["J1_E", "J2_E", "J3_E", "J4_E", "J5_E"] # joints to be moved

#red_ratio: [0.00625, 0.00625, 0.0083333, 0.00625, 0.0083333]  # gear reduction ratio of the actuator (always <=1)

#K_t: [0.14, 0.14, 0.14, 0.14, 0.14]
#rotor_MoI: [3.26e-4, 3.26e-4, 1.51e-4, 3.26e-4, 1.51e-4]
#K_d0: [0.0, 0.0, 0.0, 0.0, 0.0]
#K_d1: [0.0, 0.0, 0.0, 0.0, 0.0]

#K_t_ig: [0.0, 0.0, 0.0, 0.0, 0.0]
#rot_MoI_ig: [0.0, 0.0, 0.0, 0.0, 0.0]
#K_d0_ig: [0.0, 0.0, 0.0, 0.0, 0.0] # initial guess for the static friction torque coefficient ( tau_d0 = K_d* sign(joint_vel) )
#K_d1_ig: [0.0, 0.0, 0.0, 0.0, 0.0] # initial guess for the dynamical friction torque coefficient ( tau_d1 = K_d* joint_vel )

#K_t_nom: [0.14, 0.14, 0.14, 0.14, 0.14]
#rot_MoI_nom: [3.26e-4, 3.26e-4, 1.51e-4, 3.26e-4, 1.51e-4]
#K_d0_nom: [0.0, 0.0, 0.0, 0.0, 0.0] # initial guess for the static friction torque coefficient ( tau_d0 = K_d* sign(joint_vel) )
#K_d1_nom: [0.0, 0.0, 0.0, 0.0, 0.0] # initial guess for the dynamical friction torque coefficient ( tau_d1 = K_d* joint_vel )
